---
name: Verify

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        container:
          - node-red

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect Change
        uses: dorny/paths-filter@v2
        id: detect-change
        with:
          filters: |
            changed:
              - 'containers/${{ matrix.container }}/**'
              - 'containers/NODE_RED_VERSION'

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: containers/${{ matrix.container }}/Dockerfile
          config: containers/.hadolint.yml

  container:
    runs-on: ubuntu-latest
    name: Build Container Image
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        container:
          - node-red

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect Change
        uses: dorny/paths-filter@v2
        id: detect-change
        with:
          filters: |
            changed:
              - 'containers/${{ matrix.container }}/**'

      - name: Build ${{ matrix.container }}
        id: image
        if: steps.detect-change.outputs.changed == 'true'
        uses: ./.github/actions/container
        with:
          container: ${{ matrix.container }}
          token: ${{ secrets.GITHUB_TOKEN }}
          build: false
